(function(root){'use strict';
const categories=[['ai','AI 与生成式 AI 基础',10,4,2],['position','ADP 产品定位与能力边界',7,2,2],['core','ADP 核心功能与应用搭建',22,12,2],['design','场景理解与方案设计',25,10,5],['industry','行业解决方案与案例落地',15,6,3],['delivery','交付实施、评测与运维',11,2,4],['security','安全合规与责任 AI',10,4,2]].map(([id,name,weight,single,multi])=>({id,name,weight,single,multi}));
const equal=(a,b)=>Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&[...a].sort().every((v,i)=>v===[...b].sort()[i]);
function grade(questions,answers){const byCategory=Object.fromEntries(categories.map(c=>[c.id,{...c,earned:0,total:0,correct:0,count:0}]));let score=0;const details=questions.map(q=>{const selected=answers[q.id]||[];const correct=equal(selected,q.answer);const earned=correct?q.points:0;score+=earned;const c=byCategory[q.category];c.earned+=earned;c.total+=q.points;c.count++;c.correct+=Number(correct);return{id:q.id,selected,correct,earned};});return{score,passed:score>=70,details,categories:Object.values(byCategory),correct:details.filter(d=>d.correct).length,unanswered:details.filter(d=>!d.selected.length).length};}
function remaining(startedAt,now=Date.now()){return Math.max(0,3600000-(now-startedAt));}
function selectAnswer(q,previous,index){if(!Number.isInteger(index)||index<0||index>=q.options.length)throw Error('选项无效');if(q.type==='single')return[index];return(previous.includes(index)?previous.filter(x=>x!==index):[...previous,index]).sort();}
function validSession(s,bank){if(!s||s.version!==bank.version||!Number.isInteger(s.paperId)||s.paperId<1||s.paperId>Math.max(0,...bank.questions.map(q=>q.paper))||!Number.isFinite(s.startedAt))return false;const qs=bank.questions.filter(q=>q.paper===s.paperId);if(qs.length!==60)return false;return Object.entries(s.answers||{}).every(([id,a])=>{const q=qs.find(q=>q.id===id);return q&&Array.isArray(a)&&new Set(a).size===a.length&&a.every(n=>Number.isInteger(n)&&n>=0&&n<q.options.length)&&(q.type!=='single'||a.length<=1);});}
const api={categories,equal,grade,remaining,selectAnswer,validSession};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.FDECore=api;
})(typeof globalThis!=='undefined'?globalThis:this);
